### ISSUE TITLE
windows.onload in public.js conflict with other plugins

### ISSUE THREAD

**Issue by louisgan** [mailerlite/woo-mailerlite#20]
Hi,

Found an issue in public/js/public.js

Seems that the way windows.onload is used in public.js causes other plugins that also uses the  onload function to not load correctly. This can be further explain in the tutorials below:

https://solidlystated.com/scripting/multiple-window-onload-events-with-javascript/
https://zhuanlan.zhihu.com/p/24349496

Solution: Use jQuery ready function

**Comment by npetrunova** [comment]
Thank you for bringing this to our attention. We have addressed it in v1.4.6
