### ISSUE TITLE
Cannot redeclare Clue\StreamFilter\register()

### ISSUE THREAD

**Issue by emilleszczak2** [mailerlite/woo-mailerlite#26]
The problem is connected with old composer dependencies in "mailerlite/mailerlite-api-v2-php-sdk": "^0.2.1".

`Fatal error: Cannot redeclare Clue\StreamFilter\register() (previously
declared in
/home/serwe168/domains/xxxxxxxxxx/public_html/sklep/wp-content/plugins/xxxxxxxx/vendor/clue/stream-filter/src/functions.php:140)
in
/home/serwe168/domains/xxxxxxxxxx/public_html/sklep/wp-content/plugins/woo-mailerlite/vendor/clue/stream-filter/src/functions.php
on line 127"`

Solution: 
composer update and release new version

**Comment by johnkelesidis** [comment]
latest version of the plugin should fix this. Please update.
